name: Test

on:
  push:
    branches: ["main", "feat/geo-redirect"] # Temp added feat/geo-redirect to test playwright tests on Github
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Cancel previous runs of this workflow
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          npm install
      - name: build
        run: npm run build
      - name: JS tests
        run: npm run js-test
      - name: Start WP env
        run: npm run env start
      - name: PHP tests
        run: npm run php-test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Playwright e2e tests
        run: npm run playwright-test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
